/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionStatusEnum } from '../models/TransactionStatusEnum';
import { HttpFile } from '../http/http';

export class CashOutResponse {
    'phoneNumber': string;
    'amount': number;
    'fullName': string;
    'status': TransactionStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "fullName",
            "baseName": "full_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TransactionStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CashOutResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


