/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetOneTransaction } from '../models/GetOneTransaction';
import { HttpFile } from '../http/http';

export class GetAllTransaction {
    'transactions': Array<GetOneTransaction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<GetOneTransaction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetAllTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}
