/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Wallet } from '../models/Wallet';
import { HttpFile } from '../http/http';

export class GetAccountResponse {
    'accountNumber': string;
    'balance': number;
    'accountIsActivate': boolean;
    'methodOfPayment': Wallet;
    'loyaltyCredit': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accountNumber",
            "baseName": "account_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number",
            "format": ""
        },
        {
            "name": "accountIsActivate",
            "baseName": "account_is_activate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "methodOfPayment",
            "baseName": "method_of_payment",
            "type": "Wallet",
            "format": ""
        },
        {
            "name": "loyaltyCredit",
            "baseName": "loyalty_credit",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetAccountResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


