/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TransactionResponse {
    'orderId': string;
    'methodOfPayment': Array<string>;
    'amount'?: number;
    'amountToPay'?: number;
    'currency': string;
    'createdAt': string;
    'transactionStatus'?: string;
    'isEscrow'?: boolean;
    'isMerchant'?: boolean;
    'checkoutUrl': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "methodOfPayment",
            "baseName": "method_of_payment",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "amountToPay",
            "baseName": "amount_to_pay",
            "type": "number",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionStatus",
            "baseName": "transaction_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "isEscrow",
            "baseName": "is_escrow",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMerchant",
            "baseName": "is_merchant",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "checkoutUrl",
            "baseName": "checkout_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
