/**
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductModel } from '../models/ProductModel';
import { Wallet } from '../models/Wallet';
import { HttpFile } from '../http/http';

export class TransactionRequest {
    'methodOfPayment': Array<Wallet>;
    'products': Array<ProductModel> | null;
    'successUrl'?: string | null;
    'errorUrl'?: string | null;
    'isEscrow'?: boolean;
    'isMerchant'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "methodOfPayment",
            "baseName": "method_of_payment",
            "type": "Array<Wallet>",
            "format": ""
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<ProductModel>",
            "format": ""
        },
        {
            "name": "successUrl",
            "baseName": "success_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "errorUrl",
            "baseName": "error_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "isEscrow",
            "baseName": "is_escrow",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMerchant",
            "baseName": "is_merchant",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
